language: rust

dist: xenial

cache: cargo

addons:
    apt:
        packages:
            # packages needed for the seL4 build
            - ninja-build
            - libxml2-utils
            # cross compilers
            - gcc-arm-linux-gnueabi

rust:
    - nightly

env:
    global:
        - RUST_TARGET_PATH=${TRAVIS_BUILD_DIR}
    matrix:
        - TARGET=host
        - TARGET=armv7-unknown-none-eabi
          #- TARGET=aarch64-unknown-none-elf
          #- TARGET=x86_64-unknown-none-elf

before_install:
    - pip install --user sel4-deps
    - rustup component add rust-src
    - cargo install cargo-update || true
    - cargo install-update -i cargo-xbuild cargo-update

install:
    - if [ $TARGET == "host" ]; then
        cargo build --verbose;
      else
        cargo xbuild --target ${TARGET} --verbose;
      fi

script:
    - if [ $TARGET == "host" ]; then
        cargo test --verbose;
      else
        cargo xbuild --target ${TARGET} --verbose --release
        && cargo xbuild --target ${TARGET} --verbose --package sel4-sys --example smoketest
        && find . -path './sel4-plat-*/Cargo.toml' -exec 
                cargo xbuild --target ${TARGET} --verbose --manifest-path {} --features verified-class
            \;
        ;
      fi

