language: rust

dist: xenial

cache: cargo

addons:
    apt:
        packages:
            # packages needed for the seL4 build
            - ninja-build
            - libxml2-utils
            # cross compilers
            - gcc-arm-linux-gnueabi

rust:
    - nightly

before_install:
    - pip install --user sel4-deps
