language: rust

dist: xenial

cache: cargo

addons:
    apt:
        packages:
            # packages needed for the seL4 build
            - ninja-build
            - libxml2-utils
            # cross compilers
            - gcc-arm-linux-gnueabi
            - libc6-dev-armel-cross
            - gcc-aarch64-linux-gnu
            - libc6-dev-arm64-cross
            # testing tools for elf-preload
            - elfutils

rust:
    - nightly

env:
    matrix:
        - CI_TASK=workspace-ci-flow
        - CI_TASK=workspace-ci-aarch64-flow
        - CI_TASK=workspace-ci-armv7-flow
        - CI_TASK=workspace-ci-x86_64-flow

script:
    - which cargo-make || cargo install cargo-make
    - cargo make ${CI_TASK}

deploy:
    provider: pages
    github-token: $GITHUB_TOKEN # Set in Travis repository settings
    local-dir: target/design
    skip_cleanup: true
    on:
        branch: master
        condition: "$CI_TASK == workspace-ci-flow"
