extend = "../Makefile.toml"

[tasks.post-xbuild]
run_task = "xbuild-smoketest"

[tasks.xbuild-smoketest]
description = "Runs cargo xbuild to build the smoketest example"
category = "Build"
command = "cargo"
args = ["xbuild", "--verbose", "--example", "smoketest", "--target", "${XBUILD_TARGET}"]
condition = { env_set = ["XBUILD_TARGET"] }
dependencies = ["install-rust-src"]
