[package]
authors = ["Steven Bosnick <sbosnick@sympatico.ca>"]
build = "build.rs"
edition = "2018"
name = "sel4-plat-pc99"
version = "0.1.0"

[build-dependencies]

[build-dependencies.sel4-build]
optional = false
path = "../sel4-build"

[dependencies]
cty = "0.1.5"
