# ---- Artifact Project Settings ----

# Paths containing artifact markdown/toml files
artifact_paths = ["design"]

# Paths to exclude when loading artifacts
exclude_artifact_paths = []

# Paths containing code that has artifact links
code_paths = [
    "sel4-sys/Cargo.toml", 
    "sel4-sys/src/lib.rs",
    "sel4-sys/build.rs",
    "sel4-sys/tests/platform.rs",
    "sel4-sys/examples/smoketest.rs",
    "sel4-build/src/lib.rs",
    "sel4-plat-pc99/src/lib.rs",
    "sel4-plat-sabre/src/lib.rs",
    "sel4-plat-omap3/src/lib.rs",
    "sel4-plat-am335x/src/lib.rs",
    "sel4-plat-exynos4/src/lib.rs",
    "sel4-plat-exynos5410/src/lib.rs",
    "sel4-plat-exynos5422/src/lib.rs",
    "sel4-plat-exynos5250/src/lib.rs",
    "sel4-plat-apq8064/src/lib.rs",
    "sel4-plat-wandq/src/lib.rs",
    "sel4-plat-imx7sabre/src/lib.rs",
    "sel4-plat-zynq7000/src/lib.rs",
    "sel4-plat-zynqmp/src/lib.rs",
    "sel4-plat-ultra96/src/lib.rs",
]

# Paths to exclude when searching through code
exclude_code_paths = []
