# ---- Artifact Project Settings ----

# Paths containing artifact markdown/toml files
artifact_paths = ["design"]

# Paths to exclude when loading artifacts
exclude_artifact_paths = []

# Paths containing code that has artifact links
code_paths = [
    "sel4-sys/Cargo.toml", 
    "sel4-sys/src/lib.rs",
    "sel4-sys/build.rs"]

# Paths to exclude when searching through code
exclude_code_paths = []
