[package]
name = "elf-preload"
version = "0.1.0"
authors = ["Steven Bosnick <sbosnick@sympatico.ca>"]
edition = "2018"

[dependencies]
goblin = "0.0.21"
failure = "0.1.5"
itertools = "0.8.0"
scroll = "0.9.2"

[dev-dependencies]
assert_matches = "1.3.0"
tempfile = "3.0.8"
