#!/usr/bin/env bash

# Copyright 2019 Steven Bosnick
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE-2.0 or
# http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms

set -ev

if [[ $# -lt 2 ]]; then
    cat <<- EOF
    usage: $0 artifact_version install_prefix
EOF
    exit
fi

art_slug=vitiral/artifact

art_version=$1
install_prefix=$2

# get and untar the release archive
art_release=https://github.com/${art_slug}/releases/download/v${art_version}/artifact-v${art_version}-x86_64-unknown-linux-gnu.tar.gz

wget -qO - ${art_release} | tar xzv -C ${install_prefix}
